name: openhands-app
region: nyc

services:
  # Backend Service - Python/FastAPI
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: mnt-future2020/iSuite-CodeX

    # Use Dockerfile to avoid package manager auto-detection
    dockerfile_path: Dockerfile.digitalocean

    http_port: 3000

    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /api/options/models
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: WORKSPACE_BASE
        value: /workspace
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: ghcr.io/all-hands-ai/runtime:0.20-nikolaik
      - key: SANDBOX_USER_ID
        value: "1000"
      - key: RUN_AS_OPENHANDS
        value: "true"
      - key: LOG_ALL_EVENTS
        value: "false"

      # LLM Configuration (Add your API keys in DigitalOcean dashboard)
      - key: LLM_MODEL
        value: anthropic/claude-3-5-sonnet-20241022
        type: SECRET
      - key: LLM_API_KEY
        type: SECRET

      # Session Secret (Generate a random string)
      - key: OH_SECRET_KEY
        type: SECRET

  # Frontend Service - Static Site
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: mnt-future2020/iSuite-CodeX

    build_command: |
      cd frontend
      npm install
      npm run build

    static_sites:
      - name: frontend-static
        build_command: cd frontend && npm run build
        output_dir: frontend/build
        catchall_document: index.html
        routes:
          - path: /

    envs:
      - key: VITE_BACKEND_URL
        value: ${backend.PUBLIC_URL}
      - key: VITE_MOCK_API
        value: "false"
