name: openhands-app
region: nyc

services:
  # Backend Service - Python/FastAPI
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: mnt-future2020/iSuite-CodeX

    # Specify buildpack explicitly
    build_command: |
      echo "Installing Poetry..."
      pip install poetry
      echo "Installing dependencies..."
      poetry config virtualenvs.create false
      poetry install --without evaluation --without llama-index
      echo "Building frontend..."
      cd frontend && npm install && npm run build

    run_command: |
      uvicorn openhands.server.listen:app --host 0.0.0.0 --port 3000

    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 3000

    health_check:
      http_path: /api/options/models
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: WORKSPACE_BASE
        value: /workspace
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: ghcr.io/all-hands-ai/runtime:0.20-nikolaik
      - key: SANDBOX_USER_ID
        value: "1000"
      - key: RUN_AS_OPENHANDS
        value: "true"
      - key: LOG_ALL_EVENTS
        value: "false"

      # Disable UV package manager
      - key: UV_NO_CACHE
        value: "1"
      - key: POETRY_VIRTUALENVS_CREATE
        value: "false"

      # LLM Configuration (Add your API keys in DigitalOcean dashboard)
      - key: LLM_MODEL
        value: anthropic/claude-3-5-sonnet-20241022
        type: SECRET
      - key: LLM_API_KEY
        type: SECRET

      # Session Secret (Generate a random string)
      - key: OH_SECRET_KEY
        type: SECRET

  # Frontend Service - Static Site
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: mnt-future2020/iSuite-CodeX

    build_command: |
      cd frontend
      npm install
      npm run build

    static_sites:
      - name: frontend-static
        build_command: cd frontend && npm run build
        output_dir: frontend/build
        catchall_document: index.html
        routes:
          - path: /

    envs:
      - key: VITE_BACKEND_URL
        value: ${backend.PUBLIC_URL}
      - key: VITE_MOCK_API
        value: "false"
